version: '3'

# sudo chmod ugo+rwx data/redis/dump.rdb
services:
  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./data/redisinsight:/db
  #   restart: always

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data

  motus1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - SCORE_URI=http://localhost:4001
      - API_PATH=./data/liste_francais_utf8.txt

  motus2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - API_PATH=./data/liste_francais_utf8.txt

  score:
    build: ./../score
    ports:
      - "4001:4000"
    environment:
      - REDIS=redis://redis:6379

  auth:
    build: ./../auth
    ports:
      - "5001:5000"
    environment:
      - REDIS=redis://redis:6379

  haproxy:
    build: 
      context: .
      dockerfile: Dockerfile-haproxy
    ports:
      - "8080:80"
      - "8404:8404"
    depends_on:
      - motus1
      - motus2
      - score
      - auth
    restart: always
