version: '3'

# sudo chmod ugo+rwx  data/redis/dump.rdb

services:
  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - redis
  #   volumes:
  #     - ./data/redisinsight:/db
  #   restart: always

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - monitor-net

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - 3100:3100
    restart: unless-stopped
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - 9100:9100
    networks:
      - monitor-net

  motus1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - API_PATH=./data/liste_francais_utf8.txt
      - SCORE_URI=http://score:4000
      - OAUTH_URI=http://localhost:7001
      - OAUTH_SERVER=http://oauth:7000
      - REDIRECT_URI=http://localhost:3001/callback
      - SECRET=86df22ac950509a707889e789b12e3c9e579046729f9350e14f13c0f8292820c
      - CLIENTID=gXUa6lPsEV9o568LVdwVdEu8OXagpxjA

  motus2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - API_PATH=./data/liste_francais_utf8.txt
      - SCORE_URI=http://score:4000
      - OAUTH_URI=http://localhost:7001
      - OAUTH_SERVER=http://oauth:7000
      - REDIRECT_URI=http://localhost:3001/callback
      - SECRET=86df22ac950509a707889e789b12e3c9e579046729f9350e14f13c0f8292820c
      - CLIENTID=gXUa6lPsEV9o568LVdwVdEu8OXagpxjA

  score:
    build: ./../score
    ports:
      - "4001:4000"
    environment:
      - REDIS=redis://redis:6379

  auth:
    build: ./../auth
    ports:
      - "5001:5000"
    environment:
      - REDIS=redis://redis:6379

  oauth:
    build: ./../oauth
    ports:
      - "7001:7000"
    environment:
      - REDIS=redis://redis:6379
      - SECRET=86df22ac950509a707889e789b12e3c9e579046729f9350e14f13c0f8292820c
      - CLIENTID=gXUa6lPsEV9o568LVdwVdEu8OXagpxjA
      - REDIRECT_URI=http://localhost:3001/callback
    

  haproxy:
    build: 
      context: .
      dockerfile: Dockerfile-haproxy
    ports:
      - "8080:80"
      - "8404:8404"
    depends_on:
      - motus1
      - motus2
      - score
      - auth
      - oauth
    restart: always

networks:
  monitor-net:
